### ISSUE TITLE
Use the tob image as part of the base?

### ISSUE THREAD

**Issue by Deivitto** [Deivitto/auditor-docker#12]
Their installation of their packages should be clean on manticore, echidna, etc, maybe doing that copy pasting logic using multiple docker machines. Need more research

**Comment by luksgrin** [comment]
Won't this break the underlying ubuntu version?

**Comment by Deivitto** [comment]
Afaik it's just about copy pasting some installation files / configs from their image into our, but the ubuntu version would still be our.

So basically it's like building their image in a temporary one and you take what you want from it into yours. However I see no priority onto this right now

**Comment by Deivitto** [comment]
I don't see this really worth anymore, closing it.
