### ISSUE TITLE
create branches for different versions of the docker machine

### ISSUE THREAD

**Issue by Deivitto** [Deivitto/auditor-docker#15]
Branches options that may make sense
- General version (default)
- Formal verification version
- Static analyzers
- Trail of bits version? Makes sense since the https://github.com/trailofbits/eth-security-toolbox/tree/master doesnt have foundry, cargo, and all other tools
- ...?
-

**Comment by luksgrin** [comment]
I think it's a good idea. But I wouldn't prioritize it over other issues

**Comment by Deivitto** [comment]
Last main: https://github.com/Deivitto/auditor-docker/commit/0ffc06d2a51ef0285e70459d2d57b51c7fcc8184
Lightweight: https://github.com/Deivitto/auditor-docker/commit/39ef0e2dd2a04cd46264e34e533346e8ac9caee4
Zk: https://github.com/Deivitto/auditor-docker/commit/fe9ea4486aa7d3428a7f39353c865da236353e63
