### ISSUE TITLE
`pip3` is broken

### ISSUE THREAD

**Issue by luksgrin** [Deivitto/auditor-docker#17]
The `pip3` alias is defined within `.bashrc` as follows:

```bash
alias pip3="pip3.9"
```

This does not work. I imagine the intention is to use `python3.9`'s corresponding `pip`. The fix is:

```diff
- alias pip3="pip3.9"
+ alias pip3="python3 -m pip"
```

This only works because earlier `python3` has been defined as an alias for `python3.9`. Cool feature is that if `python3` points towards a different `python` version in the future, this alias will adapt appropriately.

Also, I would remove `alias python3.9-pip='python3.9 -m pip'` because it's obsolete given the fix above.

**Comment by Deivitto** [comment]
fixed at https://github.com/Deivitto/auditor-docker/pull/20
