### ISSUE TITLE
local `.bin` for shady executables?

### ISSUE THREAD

**Issue by luksgrin** [Deivitto/auditor-docker#18]
So I wanted to try ToB's [`medusa`](https://github.com/crytic/medusa). I downloaded and unzipped the latest release, and had a nice binary. So, for the sake of order, I did:

```bash
mkdir /home/whitehat/.bin
mv medusa /home/whitehat/.bin/.
echo 'export PATH="$PATH:/home/whitehat/.bin"' >> /home/whitehat/.bashrc
source .bashrc
```

**TLDR;**

Is it worth it to add a `.bin` directory and adding it to `$PATH` for these scenarios?
<details>
<summary>Want to know my opinion?</summary>
Everyone should be fluent with Linux systems, thus they should be capable of doing these things...
So I would not include this feature lol
</details>

**Comment by Deivitto** [comment]
Well, I wouldn't mind creating a script to move binaries into .bin with your code. I would use it for my "daily" (let's say monthly) but I don't think it's worth to add more scripts that regular users are not going to use.

However, from this I take into account Medusa fuzzer. Doesn't look hard / harmful to add it to the installer as it is not the most common fuzzer right now.

**Comment by Deivitto** [comment]
Added medusa installer with medusa in the path located at /usr/local/bin/:
https://github.com/Deivitto/auditor-docker/commit/cb47167b3575f05544486b499a71d01e34c959ca
